In [3]:
import numpy as np

x = np.array([' akash'])
print(x)

[' akash']


In [4]:
x = [1,2,3,4,5,6]
print(x)
y = np.array(x)
print(y)
print(y.ndim)
y

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
1


array([1, 2, 3, 4, 5, 6])

In [5]:
l =[]
for i in range(1,5):
    int_1 = input('Enter :')
    l.append(int_1)

print(np.array(l))


['5' '5' '5' '5']


In [6]:
k = []
for i in range(1,5):
    str_1 = input('enter :')
    k.append(str_1)

print(np.array(k))

['5' '5' '5' '5']


In [7]:
aka = np.array([[1,2,3,4],[4,5,6,9]])
print(aka)
print(type(aka))
print(aka.ndim)
print(aka.shape)

[[1 2 3 4]
 [4 5 6 9]]
<class 'numpy.ndarray'>
2
(2, 4)


In [8]:
aar = np.array([1,2,3],ndmin=10)
print(aar)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [9]:
pip = np.array([1,2,3,4],ndmin = 22)
print(pip)
print(pip.ndim)

[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]
22


In [10]:
arr_zeros = np.zeros((3,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [16]:
arr = np.array([2,3,5],ndmin =6)
print(arr)

[[[[[[2 3 5]]]]]]


In [18]:
var =np.array([1,2,3,4])
print(type(var.dtype))

<class 'numpy.dtypes.Int32DType'>


In [19]:
var1 = np.array(['a','b'])
print(var1.dtype)

<U1


In [21]:
# change  data type
x = np.array([1,2,3,4],dtype= np.int8)
print(x.dtype)

int8


In [25]:
# change  data type
x = np.array([1,2,3,4],dtype= 'f')
print(x.dtype)

float32
