In [14]:
import numpy as np

x = np.array([' akash'])
print(x)

[' akash']


In [31]:
x = [1,2,3,4,5,6]
print(x)
y = np.array(x)
print(y)
print(y.ndim)
y

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
1


array([1, 2, 3, 4, 5, 6])

In [32]:
l =[]
for i in range(1,5):
    int_1 = input('Enter :')
    l.append(int_1)

print(np.array(l))


['d' 'd' 'd' 'd']


In [27]:
k = []
for i in range(1,5):
    str_1 = input('enter :')
    k.append(str_1)

print(np.array(k))

['akash' 'sonu' 'shivam' 'monu']


In [45]:
aka = np.array([[1,2,3,4],[4,5,6,9]])
print(aka)
print(type(aka))
print(aka.ndim)
print(aka.shape)

[[1 2 3 4]
 [4 5 6 9]]
<class 'numpy.ndarray'>
2
(2, 4)


In [48]:
aar = np.array([1,2,3],ndmin=10)
print(aar)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [52]:
pip = np.array([1,2,3,4],ndmin = 22)
print(pip)
print(pip.ndim)

[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]
22


In [55]:
arr_zeros = np.zeros((3,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [73]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]
