In [2]:
import numpy as np


In [3]:
# 1- Write a NumPy program to create an array of 10 zeros.

myarray = np.zeros (10)
myarray


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 2- Write a NumPy program to create an array of 10 ones
onearray =np.ones(10)
onearray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 3- Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8


matrix = np.random.randint(0,8,(3,3))
print(matrix)

[[3 7 3]
 [4 6 1]
 [2 3 3]]


In [6]:
# 4- Write a NumPy program to reverse an array (first element becomes the last)

G_array = np.array([1,2,3,4])
reversed_array =np.flip(G_array)

print(reversed_array)

[4 3 2 1]


In [7]:
# 5- Write a NumPy program to extract all odd numbers from an array.

array = np.arange(0,15)
for i in array:
    if i%2 ==0:
        print(i)

0
2
4
6
8
10
12
14


In [8]:
# 6- Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

array = np.arange(9)
print(array)
print("mean",np.mean(array))
print("sum", np.sum(array))
print("standard deviation", np.std(array))

[0 1 2 3 4 5 6 7 8]
mean 4.0
sum 36
standard deviation 2.581988897471611


In [9]:
# 7- Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

a = np.random.randint(10,30,(5,5))
print(a)

print("min",np.min(a))
print("max",np.max(a))


[[28 27 13 23 28]
 [11 21 19 19 15]
 [18 10 11 13 18]
 [16 17 29 10 17]
 [21 17 26 26 10]]
min 10
max 29


In [10]:
# 8- Write a NumPy program to create a 2D array with 1 on the border and 0 inside.


pro= np.ones((5,5))
pro[1:-1,1:-1] = 0
print(pro)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# 9- Write a NumPy program to multiply two given matrices.

array = np.random.randint(1,15,(5,5))
array1 = np.random.randint(1,15,(5,5))
print(array)
print(array1)
print()
print("The multiplication of two matrices", array * array1)

[[ 4  7  5  1  1]
 [ 2 10 11  5  6]
 [ 5  2  8 12 13]
 [11  2 12 12  1]
 [ 8  1  9 13  1]]
[[ 3 11  1  2  7]
 [ 7 11  7  4  1]
 [12 14  4  2  4]
 [ 6  6 14  3 11]
 [13  6  5 11 14]]

The multiplication of two matrices [[ 12  77   5   2   7]
 [ 14 110  77  20   6]
 [ 60  28  32  24  52]
 [ 66  12 168  36  11]
 [104   6  45 143  14]]


In [12]:
# 10- Write a NumPy program to find the unique elements of an array

print(np.unique(array))

[ 1  2  4  5  6  7  8  9 10 11 12 13]


In [13]:
# 11- Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

arr = np.random.randint(1,10,(5,5))
print(arr)
arr1= arr[:,0::2]
print(arr1)


[[7 7 1 2 1]
 [8 6 5 5 9]
 [3 8 6 9 2]
 [3 7 2 5 6]
 [7 7 9 5 9]]
[[7 1 1]
 [8 5 9]
 [3 6 2]
 [3 2 6]
 [7 9 9]]


In [ ]:
# 12- Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

In [15]:
# 13- Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive)

In [19]:
# 14- Write a NumPy program to reverse the order of elements in each column of a 2D array.

array6 = np.random.randint(1,10,(5,5))
print(array6)
array6 = array6[:,::-1]
print(array6)

[[4 5 1 6 1]
 [3 6 1 8 7]
 [5 3 8 7 1]
 [2 9 5 3 2]
 [7 5 4 1 9]]
[[1 6 1 5 4]
 [7 8 1 6 3]
 [1 7 8 3 5]
 [2 3 5 9 2]
 [9 1 4 5 7]]


In [17]:
# 15- Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be square

In [18]:
#15

np.diag([1,2,3,4])


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])