In [2]:
import numpy as np


In [3]:
# 1- Write a NumPy program to create an array of 10 zeros.

myarray = np.zeros (10)
myarray


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 2- Write a NumPy program to create an array of 10 ones
onearray =np.ones(10)
onearray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 3- Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8


matrix = np.random.randint(0,8,(3,3))
print(matrix)

[[7 2 6]
 [6 0 5]
 [1 2 0]]


In [6]:
# 4- Write a NumPy program to reverse an array (first element becomes the last)

G_array = np.array([1,2,3,4])
reversed_array =np.flip(G_array)

print(reversed_array)

[4 3 2 1]


In [7]:
# 5- Write a NumPy program to extract all odd numbers from an array.

array = np.arange(0,15)
for i in array:
    if i%2 ==0:
        print(i)

0
2
4
6
8
10
12
14


In [8]:
# 6- Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

array = np.arange(9)
print(array)
print("mean",np.mean(array))
print("sum", np.sum(array))
print("standard deviation", np.std(array))

[0 1 2 3 4 5 6 7 8]
mean 4.0
sum 36
standard deviation 2.581988897471611


In [9]:
# 7- Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

a = np.random.randint(10,30,(5,5))
print(a)

print("min",np.min(a))
print("max",np.max(a))


[[22 21 21 14 28]
 [16 21 11 29 27]
 [28 10 15 20 14]
 [18 20 27 24 25]
 [23 18 13 11 23]]
min 10
max 29


In [10]:
# 8- Write a NumPy program to create a 2D array with 1 on the border and 0 inside.


pro= np.ones((5,5))
pro[1:-1,1:-1] = 0
print(pro)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# 9- Write a NumPy program to multiply two given matrices.

array = np.random.randint(1,15,(5,5))
array1 = np.random.randint(1,15,(5,5))
print(array)
print(array1)
print()
print("The multiplication of two matrices", array * array1)

[[ 6  3  8  4  6]
 [ 9  5 12  1  4]
 [ 3 11  4  1 14]
 [12  7  9 12  2]
 [14 13  8  8  7]]
[[12  4  8  8  6]
 [ 4  5  3 14  7]
 [11 12  2  9  9]
 [11  6  1 13  6]
 [10  4 14  5  8]]

The multiplication of two matrices [[ 72  12  64  32  36]
 [ 36  25  36  14  28]
 [ 33 132   8   9 126]
 [132  42   9 156  12]
 [140  52 112  40  56]]


In [12]:
# 10- Write a NumPy program to find the unique elements of an array

print(np.unique(array))

[ 1  2  3  4  5  6  7  8  9 11 12 13 14]


In [13]:
# 11- Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

arr = np.random.randint(1,10,(5,5))
print(arr)
arr1= arr[:,0::2]
print(arr1)


[[3 2 1 6 3]
 [1 4 7 2 7]
 [3 5 3 9 9]
 [3 9 2 3 3]
 [2 3 1 5 8]]
[[3 1 3]
 [1 7 7]
 [3 3 9]
 [3 2 3]
 [2 1 8]]


In [20]:
# 12- Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

import numpy as np


original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12],
                           [13, 14, 15, 16]])

odd_columns = original_array[:, 1::2]

print("Original Array:")
print(original_array)

print("\nElements in Odd-Numbered Columns:")
print(odd_columns)



Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Elements in Odd-Numbered Columns:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [19]:
# 13- Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive)

import numpy as np


original_array = np.array([[1, 2, 3, 4, 5],
                           [6, 7, 8, 9, 10],
                           [11, 12, 13, 14, 15],
                           [16, 17, 18, 19, 20]])


subarray = original_array[:3, 1:5]

print("Original Array:")
print(original_array)

print("\nSubarray:")
print(subarray)



Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Subarray:
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [16]:
# 14- Write a NumPy program to reverse the order of elements in each column of a 2D array.

array6 = np.random.randint(1,10,(5,5))
print(array6)
array6 = array6[:,::-1]
print(array6)

[[8 6 4 5 8]
 [8 8 5 4 8]
 [3 3 3 7 4]
 [7 4 5 3 2]
 [3 9 9 9 2]]
[[8 5 4 6 8]
 [8 4 5 8 8]
 [4 7 3 3 3]
 [2 3 5 4 7]
 [2 9 9 9 3]]


In [17]:
# 15- Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be square

var1 = np.random.randint(1,10,(10))
print(var1)
var1_len = len(var1)
diag = np.zeros((var1_len, var1_len))

for i in range(var1_len):
    for j in range(var1_len):
        if i == j:
            diag[i,j] = var1[i]
        if i < j:
            diag[i, j] = var1[j] ** 2
print(diag)


[1 8 5 3 6 4 2 5 1 8]
[[ 1. 64. 25.  9. 36. 16.  4. 25.  1. 64.]
 [ 0.  8. 25.  9. 36. 16.  4. 25.  1. 64.]
 [ 0.  0.  5.  9. 36. 16.  4. 25.  1. 64.]
 [ 0.  0.  0.  3. 36. 16.  4. 25.  1. 64.]
 [ 0.  0.  0.  0.  6. 16.  4. 25.  1. 64.]
 [ 0.  0.  0.  0.  0.  4.  4. 25.  1. 64.]
 [ 0.  0.  0.  0.  0.  0.  2. 25.  1. 64.]
 [ 0.  0.  0.  0.  0.  0.  0.  5.  1. 64.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. 64.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  8.]]


In [18]:
#15

np.diag([1,2,3,4])


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])