In [2]:
import numpy as np


In [3]:
# 1- Write a NumPy program to create an array of 10 zeros.

myarray = np.zeros (10)
myarray


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 2- Write a NumPy program to create an array of 10 ones
onearray =np.ones(10)
onearray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 3- Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8

#listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
#listarray

matrix = np.random.randint(0,8,(3,3))
print(matrix)

[[7 1 5]
 [4 2 1]
 [7 0 1]]


In [6]:
# 4- Write a NumPy program to reverse an array (first element becomes the last)

G_array = np.array([1,2,3,4])
reversed_array =np.flip(G_array)

print(reversed_array)

[4 3 2 1]


In [7]:
# 5- Write a NumPy program to extract all odd numbers from an array.



In [8]:
#15

np.diag([1,2,3,4])


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])