Imorting

In [32]:
import numpy as np

In [45]:
# set pecision
np.set_printoptions(precision=2)

Creaing matrix

In [34]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [35]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [36]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


In [37]:
d = np.array([[[[1,2],[2,3],[5,6],[5,6],[6,7],[1,2]]]])
print(d)
print(d.ndim)
print(d.shape)

[[[[1 2]
   [2 3]
   [5 6]
   [5 6]
   [6 7]
   [1 2]]]]
4
(1, 1, 6, 2)


 - generate matrix
  - linear
     -gap based
     
  - random

In [38]:
# linear

np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [39]:
a = np.arange(1,10,.02)
print(a.shape)

(450,)


In [48]:
b = np.arange(-np.pi,np.pi,.25)
print(b)
b.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [49]:
b = np.linspace(1,10,100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [50]:
# 1d change into 2d

b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [51]:
# change into 3d

b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [52]:
print(np.random.rand(5,5))

[[0.05 0.11 0.47 0.3  0.66]
 [0.41 0.74 0.69 0.49 0.41]
 [0.36 0.66 0.68 0.46 0.7 ]
 [0.44 0.24 0.85 0.36 0.56]
 [0.86 0.64 0.4  0.83 0.35]]


In [53]:
# used

print(np.random.randint(1,200,(5,8)))

[[ 51 144 141  56 172 116 112  58]
 [163 104 116 198 143 148  52  49]
 [ 90 153 196  80   2  40 141 167]
 [103 136 108 171 113 186  15 163]
 [  3 193  79 173  27  98 157  23]]


In [57]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[3 4 4]
 [8 1 4]
 [9 2 3]]
[[5 9 9]
 [6 1 1]
 [8 8 7]]


In [58]:
x+y

array([[ 8, 13, 13],
       [14,  2,  5],
       [17, 10, 10]])

In [61]:
x - 10
#slice
#filtering

array([[-7, -6, -6],
       [-2, -9, -6],
       [-1, -8, -7]])

In [62]:
x*y

array([[15, 36, 36],
       [48,  1,  4],
       [72, 16, 21]])