Imorting

In [2]:
import numpy as np

In [3]:
# set pecision
np.set_printoptions(precision=2)

Creaing matrix

In [4]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [6]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


In [7]:
d = np.array([[[[1,2],[2,3],[5,6],[5,6],[6,7],[1,2]]]])
print(d)
print(d.ndim)
print(d.shape)

[[[[1 2]
   [2 3]
   [5 6]
   [5 6]
   [6 7]
   [1 2]]]]
4
(1, 1, 6, 2)


 - generate matrix
  - linear
     -gap based
     
  - random

In [8]:
# linear

np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [9]:
a = np.arange(1,10,.02)
print(a.shape)

(450,)


In [10]:
b = np.arange(-np.pi,np.pi,.25)
print(b)
b.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [11]:
b = np.linspace(1,10,100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [12]:
# 1d change into 2d

b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [13]:
# change into 3d

b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [14]:
print(np.random.rand(5,5))

[[0.17 0.39 0.94 0.09 0.07]
 [0.99 0.05 0.84 0.96 0.45]
 [0.   0.54 0.23 0.08 0.32]
 [0.23 0.52 0.13 0.85 0.38]
 [0.94 0.57 0.35 0.67 0.74]]


In [15]:
# used

print(np.random.randint(1,200,(5,8)))

[[198 177 138 149  94  51  60  36]
 [146 199  77 104 163 183  15  42]
 [175  76  47  78 148 170  64  63]
 [198  51 166 192 144  51 167 140]
 [ 43  99  30  42 196 142 176 170]]


In [16]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[4 7 2]
 [1 3 2]
 [5 1 2]]
[[2 9 4]
 [8 8 5]
 [9 5 4]]


In [17]:
x+y

array([[ 6, 16,  6],
       [ 9, 11,  7],
       [14,  6,  6]])

In [18]:
x - 10
#slice
#filtering

array([[-6, -3, -8],
       [-9, -7, -8],
       [-5, -9, -8]])

In [19]:
x*y

array([[ 8, 63,  8],
       [ 8, 24, 10],
       [45,  5,  8]])

In [21]:
x = np.random.randint(20,50,(6,6))
print(x)

[[46 22 42 42 30 25]
 [23 29 21 43 41 26]
 [23 41 46 21 27 25]
 [44 34 23 34 43 41]
 [41 42 46 38 45 29]
 [48 31 24 31 32 43]]


In [26]:
z = []
for i in x :
    for j in i:
        if j > 30:
            z.append(j)
print(np.array(z))

[46 42 42 43 41 41 46 44 34 34 43 41 41 42 46 38 45 48 31 31 32 43]


In [22]:
x >30 # filter

array([[ True, False,  True,  True, False, False],
       [False, False, False,  True,  True, False],
       [False,  True,  True, False, False, False],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [ True,  True, False,  True,  True,  True]])

In [23]:
print(x[x>30])  # boolean filtering

[46 42 42 43 41 41 46 44 34 34 43 41 41 42 46 38 45 48 31 31 32 43]


In [27]:
x [(x>30) &(x<45)]

array([42, 42, 43, 41, 41, 44, 34, 34, 43, 41, 41, 42, 38, 31, 31, 32, 43])

In [28]:
f1 = x >30
f2 = x <45
x[f1 &f2]

array([42, 42, 43, 41, 41, 44, 34, 34, 43, 41, 41, 42, 38, 31, 31, 32, 43])

 slicing
 1D = [start : stop : step]
 2D = [r_start:r_stop:r_step, c_start: c_stop: c_step]

In [32]:
print('first row')
print(x[0])

first row
[46 22 42 42 30 25]


In [29]:
print('last row')
print(x[-1])

last row
[48 31 24 31 32 43]


In [30]:
print('slice 2 to 5')
print(x[2:6])

slice 2 to 5
[[23 41 46 21 27 25]
 [44 34 23 34 43 41]
 [41 42 46 38 45 29]
 [48 31 24 31 32 43]]


In [33]:
print(x[:,0])

[46 23 23 44 41 48]


In [35]:
print(x[:,-1])

[25 26 25 41 29 43]


In [41]:
print(x[:,-3:])

[[42 30 25]
 [43 41 26]
 [21 27 25]
 [34 43 41]
 [38 45 29]
 [31 32 43]]
